### PR TITLE
Making minimum height configurable

### PR DESCRIPTION
**Pull request by pmosse**

### CODE REVIEW

**Comment by lautarodragan** [comment]
I think the new configuration file is missing in https://github.com/poetapp/node-conf

**Comment by pmosse** [comment]
@lautarodragan You're right, just added it.

**Comment by lautarodragan** [comment]
Two comments:

1. This PR, at this moment, is attempting to load the configuration by reading the command line args from `blockchain/domainService.ts`. Accessing command line args and loading configuration should only be done by the outer-most file in the code flow. In our case, that's the files that live in `/bin`. The configuration should then be passed down from there.

2. I made changes to how configuration is managed and added loading of configuration for db connection to claims-to-db in #295, so I'm closing this PR now and we'll start from scratch afterwards.

**Comment by pmosse** [comment]
@lautarodragan Perfect!

**Pull request closed without merging**
